### ISSUE TITLE
Mitsuba Error

### ISSUE THREAD

**Issue by wyan1103** [CMURoboTouch/mitsuba2-python-package#3] opened 2021-02-19 19:44 UTC
Traceback (most recent call last):
  File "/home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mitsuba.core_ext'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (/usr/bin/python3) that is different from the one for which the native module was compiled (/home/arpit/.pyenv/versions/py377/bin/python).

**Comment by arpit15** [comment] 2021-02-20 00:25
I think the problem is that you have `python3.8`. The package was built with `python3.7`. Can you try with the supported version?

**Comment by wyan1103** [comment] 2021-02-20 00:47
Trying it with python 3.7.9 yields the same result

**Comment by arpit15** [comment] 2021-02-20 01:20
Can you post the output of the following command?
```bash
cd dist_ubuntu20.04/python/mitsuba
ldd core_ext.cpython-37m-x86_64-linux-gnu.so
```

**Comment by wyan1103** [comment] 2021-02-23 15:04
linux-vdso.so.1 (0x00007fffc7cba000)
        libmitsuba-render.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libmitsuba-render.so (0x00007f20077ca000)
        libmitsuba-core.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libmitsuba-core.so (0x00007f20076c0000)
        libasmjit.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libasmjit.so (0x00007f200767a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2007660000)
        libtbb.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libtbb.so (0x00007f200761c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f20075f9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f20075f0000)
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f20074a1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2007480000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2007270000)
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f2007230000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2007210000)
        libpugixml.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libpugixml.so (0x00007f20071db000)
        libjpeg.so.8 => not found
        libIlmImf.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libIlmImf.so (0x00007f2006edd000)
        libHalf.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libHalf.so (0x00007f2006e98000)
        libImath.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libImath.so (0x00007f2006e87000)
        libIlmThread.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libIlmThread.so (0x00007f2007477000)
        libIex.so => /home/wyan1103/Simulation/mitsuba2-python-package/dist_ubuntu20.04/python/mitsuba/./../../libIex.so (0x00007f2006e66000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f20079dd000)
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libc++.so.1 => not found
        libc++abi.so.1 => not found

**Comment by arpit15** [comment] 2021-02-23 15:34
The issue has been resolved by installing following packages on ubuntu
`sudo apt install libc++-10-dev libc++abi-10-dev libjpeg8-dev`

**Closed as completed by arpit15** 2021-02-23 15:34 UTC
